dreamer_configs:
  - dmc_proprio

task: dmc_cheetah_run
total_steps: 500000
seed: 42

dreamer:
  batch_size: 32
  envs: 8
  compile: false

true_bias_loss:
  beta: 1.0
  n_starts: 8
  warmup_env_steps: 50000
